#!/bin/bash

function log {
  echo $(date) $ME - $@
}

function serviceConf {
  # Substitute configuration
  for VARIABLE in $(env | cut -f1 -d=); do
    VAR=${VARIABLE//:/_}
    sed -i "s={{ $VAR }}=${!VAR}=g" /etc/postfix/*.cf
  done

  # Override Postfix configuration
  if [ -f /overrides/postfix.cf ]; then
    while read line; do
      postconf -e "$line"
    done < /overrides/postfix.cf
    echo "Loaded '/overrides/postfix.cf'"
  else
    echo "No extra postfix settings loaded because optional '/overrides/postfix.cf' not provided."
  fi

  # Include table-map files
  if ls -A /overrides/*.map 1> /dev/null 2>&1; then
    cp /overrides/*.map /etc/postfix/
    postmap /etc/postfix/*.map
    rm /etc/postfix/*.map
    chown root:root /etc/postfix/*.lmdb
    chmod 0644 /etc/postfix/*.lmdb
    echo "Loaded 'map files'"
  else
    echo "No extra map files loaded because optional '/overrides/*.map' not provided."
  fi

  # Include cf files
  if ls -A /overrides/*.cf 1> /dev/null 2>&1; then
    cp /overrides/*.cf /etc/postfix/
    chown root:root /etc/postfix/*.cf
    chmod 0644 /etc/postfix/*.cf
    echo "Loaded 'cf files'"
  else
    echo "No extra cf files loaded because optional '/overrides/*.cf' not provided."
  fi
}

function serviceStart {
  serviceConf
  # Actually run Postfix
  log "[ Starting Postfix... ]"
  #exec /usr/libexec/postfix/master
  exec postfix start-fg
}

export DOMAIN=${DOMAIN:-"localhost"}
export MESSAGE_SIZE_LIMIT=${MESSAGE_SIZE_LIMIT:-"50000000"}
export RELAYNETS=${RELAYNETS:-""}
export RELAYHOST=${RELAYHOST:-""}

serviceStart
